------------------------------------------------------------------------------/
--   ____  ____ 
--  /   /\/   /
-- /___/  \  /    Vendor: Xilinx
-- \   \   \/     Version : 3.6
--  \   \         Application : 7 Series FPGAs Transceivers Wizard
--  /   /         Filename : timinggtp_common.vhd
-- /___/   /\     
-- \   \  /  \ 
--  \___\/\___\
--
--
-- Module GtpCommon 
-- Generated by Xilinx 7 Series FPGAs Transceivers Wizard
-- 
-- 
-- (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
-- 
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
-- 
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
-- 
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
-- 
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES. 

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;

use work.GtpCommonPkg.all;

--***************************** Entity Declaration ****************************

-- NOTE: the line rate is  refclk * FBDIV * FBDIV_45 * 2 / xXOUTCLK_DIV
--       with x either T or R.
--       ****************************************************************
--       * the wizard creates different values for xXOUTCLK_DIV, probably
--       * depending on other settings; double check!!!!
--       ****************************************************************
entity GtpCommon is
generic
(
    -- Simulation attributes
    WRAPPER_SIM_GTRESET_SPEEDUP     : string     :=  "TRUE";        -- Set to "true" to speed up sim reset 
    SIM_PLL0REFCLK_SEL              : bit_vector := "001";
    SIM_PLL1REFCLK_SEL              : bit_vector := "001";
    PLL0_FBDIV_IN                   : integer range 1 to 5 := 2;
    PLL1_FBDIV_IN                   : integer range 1 to 5 := 2;
    PLL0_FBDIV_45_IN                : integer range 4 to 5 := 5;
    PLL1_FBDIV_45_IN                : integer range 4 to 5 := 5;
    PLL0_REFCLK_DIV_IN              : integer range 1 to 2 := 1;
    PLL1_REFCLK_DIV_IN              : integer range 1 to 2 := 1;
	INSTANTIATE_REFCLKBUF           : boolean              := true
 );
port
(
    DRPADDR_COMMON_IN    : in std_logic_vector(7 downto 0)  := (others => '0');
    DRPCLK_COMMON_IN     : in std_logic;
    DRPDI_COMMON_IN      : in std_logic_vector(15 downto 0) := (others => '0');
    DRPDO_COMMON_OUT     : out std_logic_vector(15 downto 0);
    DRPEN_COMMON_IN      : in std_logic                     := '0'; 
    DRPRDY_COMMON_OUT    : out std_logic; 
    DRPWE_COMMON_IN      : in std_logic                     := '0';

    -- if this is unset then the DRPCLK_COMMON_IN is used
    PLLLOCKDETCLK_IN     : in std_logic_vector              := "";

    pllIb                : in  GtpCommonIbArray(1 downto 0)     := (others => GTP_COMMON_IB_INIT_C);
    pllOb                : out GtpCommonObArray(1 downto 0);

    GTREFCLK_P_IN        : in std_logic_vector(1 downto 0)  := (others => '0');
    GTREFCLK_N_IN        : in std_logic_vector(1 downto 0)  := (others => '0');
    -- indices 2..6 are east0, east1, west0, west1, gtgrefclk
    GTREFCLK_IN          : in std_logic_vector(6 downto 0)  := (others => '0');

    -- access to the refclk (only if internal buffer is instantiated).
    -- MUST be further buffered by the user when used!
    GTREFCLK_OUT         : out std_logic_vector(1 downto 0)
);

end GtpCommon;
    
architecture RTL of GtpCommon is

    attribute CORE_GENERATION_INFO : string;
    attribute CORE_GENERATION_INFO of RTL : architecture is "GtpCommon,gtwizard_v3_6_8,{protocol_file=aurora_8b10b_single_lane_2byte}";


--*************************Logic to set Attribute PLL_FB_DIV*****************************

    -- ground and tied_to_vcc_i signals
    signal  tied_to_ground_i                :   std_logic := '0';
    signal  tied_to_ground_vec_i            :   std_logic_vector(63 downto 0) := (others => '0');
    signal  tied_to_vcc_i                   :   std_logic := '1';
    signal  tied_to_vcc_vec_i               :   std_logic_vector(63 downto 0) := (others => '1');

    signal  gtRefClk_i                      :   std_logic_vector( 1 downto 0);

    signal  pllLockDetClk_i                 :   std_logic_vector( 1 downto 0);
begin
    tied_to_ground_i                    <= '0';
    tied_to_ground_vec_i(63 downto 0)   <= (others => '0');
    tied_to_vcc_i                       <= '1';
    tied_to_vcc_vec_i(63 downto 0)      <= (others => '1');

    G_REFBUF : if ( INSTANTIATE_REFCLKBUF ) generate
      G_BUFDSGTE : for i in GTREFCLK_P_IN'range generate
        U_REFBUF : IBUFDS_GTE2
          generic map (
            CLKRCV_TRST  => true, -- ug482
            CLKCM_CFG    => true, -- ug482
            CLKSWING_CFG => "11"  -- ug482
          )
          port map (
            CEB          => tied_to_ground_i,
            ODIV2        => open,
            O            => gtRefClk_i(i),
            I            => GTREFCLK_P_IN(i),
            IB           => GTREFCLK_N_IN(i)
          );

        GTREFCLK_OUT(i) <= gtRefClk_i(i);
      end generate;
    end generate G_REFBUF;

    G_NOREFBUF : if ( not INSTANTIATE_REFCLKBUF ) generate
      gtRefClk_i   <= GTREFCLK_IN(1 downto 0);
      GTREFCLK_OUT <= ( others => '0' );
    end generate G_NOREFBUF;

    G_LOCKDETCLK_0 : if ( PLLLOCKDETCLK_IN'length = 0 ) generate
      pllLockDetClk_i <= ( others => DRPCLK_COMMON_IN );
    end generate G_LOCKDETCLK_0;

    G_LOCKDETCLK_1 : if ( PLLLOCKDETCLK_IN'length = 1 ) generate
      pllLockDetClk_i <= ( others => PLLLOCKDETCLK_IN(0) );
    end generate G_LOCKDETCLK_1;

    G_LOCKDETCLK_X : if ( PLLLOCKDETCLK_IN'length > 1 ) generate
      pllLockDetClk_i <= PLLLOCKDETCLK_IN(1 downto 0);
    end generate G_LOCKDETCLK_X;

    --_________________________________________________________________________
    --_________________________________________________________________________
    --_________________________GTXE2_COMMON____________________________________

    gtpe2_common_i : GTPE2_COMMON
    generic map
    (
            -- Simulation attributes
            SIM_RESET_SPEEDUP    => WRAPPER_SIM_GTRESET_SPEEDUP,
            SIM_PLL0REFCLK_SEL   => SIM_PLL0REFCLK_SEL,
            SIM_PLL1REFCLK_SEL   => SIM_PLL1REFCLK_SEL,
            SIM_VERSION          => ("2.0"),

            PLL0_FBDIV           => PLL0_FBDIV_IN     ,	
	         PLL0_FBDIV_45        => PLL0_FBDIV_45_IN  ,	
	         PLL0_REFCLK_DIV      => PLL0_REFCLK_DIV_IN,	
	         PLL1_FBDIV           => PLL1_FBDIV_IN     ,	
	         PLL1_FBDIV_45        => PLL1_FBDIV_45_IN  ,	
	         PLL1_REFCLK_DIV      => PLL1_REFCLK_DIV_IN,	            


       ------------------COMMON BLOCK Attributes---------------
        BIAS_CFG                                =>     (x"0000000000050001"),
        COMMON_CFG                              =>     (x"00000000"),

       ----------------------------PLL Attributes----------------------------
        PLL0_CFG                                =>     (x"01F03DC"),
        PLL0_DMON_CFG                           =>     ('0'),
        PLL0_INIT_CFG                           =>     (x"00001E"),
        PLL0_LOCK_CFG                           =>     (x"1E8"),
        PLL1_CFG                                =>     (x"01F03DC"),
        PLL1_DMON_CFG                           =>     ('0'),
        PLL1_INIT_CFG                           =>     (x"00001E"),
        PLL1_LOCK_CFG                           =>     (x"1E8"),
        PLL_CLKOUT_CFG                          =>     (x"00"),

       ----------------------------Reserved Attributes----------------------------
        RSVD_ATTR0                              =>     (x"0000"),
        RSVD_ATTR1                              =>     (x"0000")

        
    )
    port map
    (
        DMONITOROUT             => open,	
        ------------- Common Block  - Dynamic Reconfiguration Port (DRP) -----------
        DRPADDR                         =>      DRPADDR_COMMON_IN,
        DRPCLK                          =>      DRPCLK_COMMON_IN,
        DRPDI                           =>      DRPDI_COMMON_IN,
        DRPDO                           =>      DRPDO_COMMON_OUT,
        DRPEN                           =>      DRPEN_COMMON_IN,
        DRPRDY                          =>      DRPRDY_COMMON_OUT,
        DRPWE                           =>      DRPWE_COMMON_IN,
        ----------------- Common Block - GTPE2_COMMON Clocking Ports ---------------
        GTEASTREFCLK0                   =>      GTREFCLK_IN(2),
        GTEASTREFCLK1                   =>      GTREFCLK_IN(3),
        GTGREFCLK1                      =>      GTREFCLK_IN(6),
        GTREFCLK0                       =>      gtRefClk_i(0),
        GTREFCLK1                       =>      gtRefClk_i(1),
        GTWESTREFCLK0                   =>      GTREFCLK_IN(4),
        GTWESTREFCLK1                   =>      GTREFCLK_IN(5),
        PLL0OUTCLK                      =>      pllOb(0).pllOutClk,
        PLL0OUTREFCLK                   =>      pllOb(0).pllOutRefClk,
        PLL1OUTCLK                      =>      pllOb(1).pllOutClk,
        PLL1OUTREFCLK                   =>      pllOb(1).pllOutRefClk,
        -------------------------- Common Block - PLL Ports ------------------------
        PLL0FBCLKLOST                   =>      open,
        PLL0LOCK                        =>      pllOb(0).pllLock,
        PLL0LOCKDETCLK                  =>      pllLockDetClk_i(0),
        PLL0LOCKEN                      =>      tied_to_vcc_i,
        PLL0PD                          =>      pllIb(0).pllPD,
        PLL0REFCLKLOST                  =>      pllOb(0).pllRefClkLost,
        PLL0REFCLKSEL                   =>      pllIb(0).pllRefClkSel,
        PLL0RESET                       =>      pllIb(0).pllReset,

        PLL1FBCLKLOST                   =>      open,
        PLL1LOCK                        =>      pllOb(1).pllLock,
        PLL1LOCKDETCLK                  =>      pllLockDetClk_i(0),
        PLL1LOCKEN                      =>      tied_to_vcc_i,
        PLL1PD                          =>      pllIb(1).pllPD,
        PLL1REFCLKLOST                  =>      pllOb(1).pllRefClkLost,
        PLL1REFCLKSEL                   =>      pllIb(1).pllRefClkSel,
        PLL1RESET                       =>      pllIb(1).pllReset,

        ---------------------------- Common Block - Ports --------------------------
        BGRCALOVRDENB                   =>      tied_to_vcc_i,
        GTGREFCLK0                      =>      tied_to_ground_i,
        PLLRSVD1                        =>      "0000000000000000",
        PLLRSVD2                        =>      "00000",
        REFCLKOUTMONITOR0               =>      open,
        REFCLKOUTMONITOR1               =>      open,
        ------------------------ Common Block - RX AFE Ports -----------------------
        PMARSVDOUT                      =>      open,
        --------------------------------- QPLL Ports -------------------------------
        BGBYPASSB                       =>      tied_to_vcc_i,
        BGMONITORENB                    =>      tied_to_vcc_i,
        BGPDB                           =>      tied_to_vcc_i,
        BGRCALOVRD                      =>      "11111",
        PMARSVD                         =>      "00000000",
        RCALENB                         =>      tied_to_vcc_i
    );
end RTL;
